#Application and user config
#Sun Aug 16 20:40:08 ART 2026
ChronometerX=22
ChronometerY=23
ConfigX=229
ConfigY=92
GameInfoX=8
GameInfoY=577
GamesListX=1077
GamesListY=6
GeneralSummaryX=989
GeneralSummaryY=607
PlayerStatisticsX=7
PlayerStatisticsY=801
SessionsHistoryX=595
SessionsHistoryY=4
WindowMaximized=0
steam.dir=C\:\\Program Files (x86)\\Steam\\steam.exe
steam.id=76561198201938341
