#Application and user config
#Fri Jul 31 23:01:53 ART 2026
ChronometerX=11
ChronometerY=4
ConfigX=1073
ConfigY=36
GameInfoX=266
GameInfoY=262
GamesListX=1604
GamesListY=6
GeneralSummaryX=1513
GeneralSummaryY=737
SessionsHistoryX=1125
SessionsHistoryY=7
WindowMaximized=1
steam.id=76561198201938341
