#Application and user config
#Sat Aug 08 21:59:25 ART 2026
ChronometerX=119
ChronometerY=253
ConfigX=229
ConfigY=92
GameInfoX=93
GameInfoY=550
GamesListX=1022
GamesListY=71
GeneralSummaryX=1513
GeneralSummaryY=737
SessionsHistoryX=135
SessionsHistoryY=55
WindowMaximized=0
steam.dir=C\:\\Program Files (x86)\\Steam\\steam.exe
steam.id=76561198201938341
